# Generated by Django 4.0.4 on 2022-04-30 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address_student',
            name='village_number',
        ),
        migrations.AddField(
            model_name='address_student',
            name='village_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address_student',
            name='soi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coop_train',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coop_train',
            name='curriculum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coop_train',
            name='datetime_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coop_train',
            name='deadline_apply',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coop_train',
            name='link_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coop_train',
            name='start_apply',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='train_contact',
            name='institute_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='train_contact',
            name='institute_tel',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$'), django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='train_contact',
            name='road',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='train_contact',
            name='soi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
