# Generated by Django 4.0.4 on 2022-04-30 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisweb', '0002_remove_address_student_village_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_student',
            name='postcode',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='coop_train',
            name='deadline_apply',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coop_train',
            name='start_apply',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
